---
on: push
name: Run tests
jobs:
  dockerfilelint:
    name: Dockerfilelint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Dockerfilelint
      uses: docker://replicated/dockerfilelint
      with:
        args: ./Dockerfile

    - name: Bats
      uses: actions/bin/bats@master
      with:
        args: ./test/*.bats

    - name: ShellCheck
      uses: actions/bin/shellcheck@master
      with:
        args: ./merge-pull-request
